export const environment = {
  domain:"https://t.f80.fr",
  mobile:true,
  height:"99vh",
  width:"100%",
  title:"The linKut App",
  production:false,
  appli:"linKut",
  server:"https://api.nfluent.io:4242",
  shorter_service:"https://x.f80.fr:31899",
  redirect_server:"https://gate.nfluent.io",
  merchant:{},
  website:"",
  faqs:"",
  company:"f80",
  version:0.1,
  connexion:{
    address: true,
    direct_connect: false,
    email: false,
    extension_wallet: true,
    google: false,
    keystore: false,
    nfluent_wallet_connect: false,
    on_device: false,
    private_key: false,
    wallet_connect: true,
    web_wallet: false,
    webcam: false
  }
}
