export const environment = {
  domain:"http://127.0.0.1:80",
  //domain: "https://t.f80.fr",
  mobile:true,
  height:"800px",
  width:"400px",
  title:"linKut",
  production:false,
  appli:"linKut",
  server:"https://api.f80.fr:4242",
  shorter_service:"http://127.0.0.1:80",
  redirect_server:"https://gate.nfluent.io",
  merchant:{},
  website:"",
  faqs:"",
  company:"f80",
  version:"0.1",
  connexion:{
    address: true,
    direct_connect: false,
    email: true,
    extension_wallet: true,
    google: true,
    keystore: false,
    nfluent_wallet_connect: false,
    on_device: false,
    private_key: false,
    wallet_connect: true,
    web_wallet: false,
    webcam: false
  }
}
