export const environment = {
  domain:"https://t.f80.fr",
  mobile:false,
  height:"700px",
  width:"350px",
  title:"linKut",
  production:true,
  appli:"linKut",
  server:"https://api.nfluent.io:4242",
  shorter_service:"https://x.f80.fr",
  redirect_server:"https://gate.nfluent.io",
  merchant:{},
  website:"",
  faqs:"",
  company:"f80",
  version:0.1,
  connexion:{
    address: true,
    direct_connect: false,
    email: false,
    extension_wallet: true,
    google: false,
    keystore: false,
    nfluent_wallet_connect: false,
    on_device: false,
    private_key: false,
    wallet_connect: true,
    web_wallet: false,
    webcam: false
  }
}
